version: "3.9"

services:
  api:
    build:
      context: .
      target: dev
    container_name: blog-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    command: npm run dev

  test:
    build:
      context: .
      target: dev
    container_name: blog-api-test
    environment:
      - NODE_ENV=test
    command: npm test
