name: Docker Build & Test

on:
  push:
    branches: [main, master, node-version]
  pull_request:
    branches: [main, master, node-version]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image (with dev deps for tests)
        run: |
          docker build -f Dockerfile.dev -t blog-api-test .

      - name: Run tests inside container
        run: |
          docker run --rm \
            -e NODE_ENV=test \
            blog-api-test \
            npm test
